name: ml-cookbook
dependencies:
- python=3.7
- ipython
- jupyter
- scikit-learn
- numpy
- matplotlib
- pandas
- opencv
- cython
- xlrd
- sqlalchemy
- beautifulsoup4
- lxml
- nltk
- seaborn
- pydotplus
- pip:
  - tensorflow-gpu
  - keras
  - fancyimpute
  - konlpy
